"""Freeze the submissions already tested into a corpus that can be re-run.

Every accuracy claim this project has made was measured against papers generated by
the same code that parses them, which is exactly how a real mathematics paper came
to extract one question out of nine. The fix for that is not a better generator: it
is to keep re-running the documents that have already been through the pipeline,
including the ones that failed, and to look at each of them after every change.

The uploaded PDFs are gone — `uploads.discard` removes them once rendered, and the
bucket's lifecycle rule would have anyway. What survives is the rendered pages, at
200 DPI, under `pages/<content_hash[:16]>/pNNNN.png`. Those are enough: rebuilt into
a PDF they go back through the pipeline as an image document, which is what a
scanned paper is in the first place.

**They expire in seven days**, which is why this exists as a script to run now
rather than a note to do it later.

One honest caveat, and it matters for reading the numbers. The stored pages are
*post*-preprocessing: already deskewed, already shadow-corrected. Re-submitting them
runs preprocessing a second time. On an already-straight page that is close to a
no-op, but it is not the identical input the original upload saw, so the first
re-run establishes a **new baseline** rather than reproducing the old numbers. Every
comparison after that is like for like, which is all a regression corpus needs.

    uv run python tooling/scripts/build_corpus.py

Writes into data/, which is not tracked — these are real student answer scripts.
"""

# ruff: noqa: E501 - the table of examples reads better one per line.

from __future__ import annotations

import argparse
import io
import json
import subprocess
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "data" / "corpus"
BUCKET = "vedaai-grader-pages-872483264706"
LIVE = "https://wvqyfdkpl1.execute-api.ap-south-1.amazonaws.com"

#: The examples, and why each one is in the set.
#:
#: Kept as a written table rather than discovered by scanning the store, because
#: what makes this a corpus is that each entry is here for a stated reason. A set
#: that grows by accident stops being a control.
EXAMPLES: list[tuple[str, str, str]] = [
    ("math-paper", "8f002f2e3938", "the user's own paper: 3-page scan, 4-page script, 9 questions of which 1 was found"),
    ("comprehension-user", "644685bab1c4", "the user's first upload, which worked"),
    ("science-full", "0c41796adea3", "18 entries, 5-page script, every edge case at once"),
    ("real-ink", "a4e2169a489f", "4 pages of genuine ASAP handwriting"),
    ("prose-matched", "dfe0e8975868", "a correctly matched pair; Q1 scored 5/5 with citations"),
    ("programming-matched", "1a4199be67da", "handwritten code, where transcription is the ceiling"),
    ("reassigned", "a8fba81f7a4a", "carries a teacher's manual correction"),
]


def fetch(sid: str) -> dict:
    with urllib.request.urlopen(f"{LIVE}/api/submissions/{sid}", timeout=40) as response:
        return json.load(response)


def pull_pages(content_hash: str, dest: Path) -> list[Path]:
    """Every rendered page for one document, in order."""
    prefix = f"pages/{content_hash[:16]}/"
    listing = subprocess.run(
        ["aws", "s3", "ls", f"s3://{BUCKET}/{prefix}"],
        capture_output=True, text=True, check=False,
    )
    names = sorted(line.split()[-1] for line in listing.stdout.splitlines() if line.strip())
    dest.mkdir(parents=True, exist_ok=True)

    out: list[Path] = []
    for name in names:
        target = dest / name
        if not target.exists():
            subprocess.run(
                ["aws", "s3", "cp", f"s3://{BUCKET}/{prefix}{name}", str(target)],
                capture_output=True, check=True,
            )
        out.append(target)
    return out


#: The tallest page edge, in points. A4 is 842, and matching it means the pipeline
#: re-renders these at about the resolution they were captured at.
_PAGE_LONG_EDGE = 842.0

#: JPEG quality for the rebuilt pages.
#:
#: Lossy on purpose. A page stacked at its native pixel size produced a 56 MB PDF —
#: past the service's own 40 MB limit, so the corpus could not be submitted at all.
#: At 88 the artefacts are far below the scale of a pen stroke and transcription is
#: unaffected, which is the only property this corpus needs to preserve.
_JPEG_QUALITY = 88


def to_pdf(pages: list[Path], destination: Path) -> None:
    """Stack page images into one PDF at a sane physical size.

    Sizing matters more than it looks. Giving each page a width in points equal to
    its width in pixels makes a 23-by-32-inch page, and the pipeline then rasterises
    *that* at 200 DPI — landing on the 4000px cap and resampling the whole document
    for nothing. Sizing to A4 means one render at roughly the original resolution.
    """
    import pymupdf

    doc = pymupdf.open()
    for image in pages:
        pixmap = pymupdf.Pixmap(str(image))
        scale = _PAGE_LONG_EDGE / max(pixmap.width, pixmap.height)
        width, height = pixmap.width * scale, pixmap.height * scale

        page = doc.new_page(width=width, height=height)
        page.insert_image(
            pymupdf.Rect(0, 0, width, height),
            stream=pixmap.tobytes("jpeg", jpg_quality=_JPEG_QUALITY),
        )
    destination.parent.mkdir(parents=True, exist_ok=True)
    doc.save(destination, deflate=True, garbage=3)
    doc.close()


def summarise(submission: dict) -> dict:
    """The handful of numbers a regression is visible in."""
    mapping = submission.get("mapping") or {}
    statuses: dict[str, int] = {}
    for entry in mapping.get("mappings", []):
        statuses[entry["status"]] = statuses.get(entry["status"], 0) + 1

    grades = submission.get("grades") or {}
    paper = submission.get("question_paper_lines") or {}
    sheet = submission.get("answer_sheet_lines") or {}

    return {
        "status": submission.get("status"),
        "questions": submission.get("question_count"),
        "question_labels": [q["label_raw"] for q in (submission.get("questions") or {}).get("questions", [])],
        "answer_pages": submission.get("answer_sheet_page_count"),
        "paper_lines": len(paper.get("lines") or []),
        "sheet_lines": len(sheet.get("lines") or []),
        "mapping": statuses,
        "orphans": len(mapping.get("orphan_block_ids") or []),
        "unassigned_ink": mapping.get("unassigned_ink_ratio"),
        "blocks": len(submission.get("blocks") or []),
        "marks": [grades.get("total_awarded"), grades.get("total_available")] if grades else None,
        "warnings": len(submission.get("warnings") or []),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--live", default=LIVE)
    args = parser.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    baseline: dict[str, dict] = {}

    for name, sid, why in EXAMPLES:
        submission = fetch(sid)
        folder = OUT / name
        print(f"\n{name}  [{sid}]")
        print(f"  {why}")

        for field, label in (("question_paper_file", "paper"), ("answer_sheet_file", "script")):
            source = submission.get(field) or {}
            content_hash = source.get("content_hash")
            if not content_hash:
                print(f"  {label}: no content hash, skipped")
                continue
            pages = pull_pages(content_hash, folder / f"{label}-pages")
            if not pages:
                print(f"  {label}: no rendered pages survive, skipped")
                continue
            pdf = folder / f"{label}.pdf"
            to_pdf(pages, pdf)
            print(f"  {label}: {len(pages)} pages -> {pdf.relative_to(ROOT)} "
                  f"({pdf.stat().st_size / 1024:.0f} kB)")

        baseline[name] = {"submission_id": sid, "why": why, "original": summarise(submission)}

    (OUT / "baseline.json").write_text(json.dumps(baseline, indent=2, sort_keys=True))
    print(f"\n  baseline written: {(OUT / 'baseline.json').relative_to(ROOT)}")
    print("  NOTE: these pages are post-preprocessing, so the first re-run sets a new")
    print("  baseline rather than reproducing the numbers above.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
